//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XGRAPH.rc
//
#define IDD_CHARTPROPERTIES             1
#define IDS_NOPOLYTREND                 1
#define IDAPPLY                         100
#define IDB_BS0                         105
#define IDD_CURVE                       106
#define IDB_BS1                         107
#define IDB_BS2                         108
#define IDD_AXIS                        109
#define IDB_BS3                         110
#define IDB_BS4                         111
#define IDB_BS5                         112
#define IDD_CHART                       113
#define IDD_LABELDLG                    116
#define IDD_AVG                         119
#define IDD_TRENDDLG                    121
#define IDC_GRAPH                       200
#define IDC_BUTTON1                     201
#define IDC_BUTTON2                     202
#define IDC_CHECK1                      203
#define IDC_BUTTON3                     204
#define IDC_CHECK2                      205
#define IDC_SPINLINESIZE                206
#define IDC_COLOR                       207
#define IDC_CBLINESTYLE                 208
#define IDC_CBVISIBLE                   209
#define IDC_NAME                        210
#define IDC_CBFILL                      211
#define IDC_CBTRANSPARENT               212
#define IDC_MAX                         213
#define IDC_CBGRID                      214
#define IDC_CBTIMEAXIS                  215
#define IDC_PRECISION                   216
#define IDC_SPINPRECISION               217
#define IDC_ARCSIZE                     218
#define IDC_SPINARCSIZE                 219
#define IDC_TICKSIZE                    220
#define IDC_SPINTICKSIZE                221
#define IDC_MARKERSIZE                  222
#define IDC_SPINMARKERSIZE              223
#define IDC_STEP                        224
#define IDC_STARTDATE                   225
#define IDC_STARTTIME                   226
#define IDC_RADIO2                      227
#define IDC_RADIO3                      228
#define IDC_ENDDATE                     229
#define IDC_ENDTIME                     230
#define IDC_RADIO6                      231
#define IDC_RADIO7                      232
#define IDC_GRIDCOLOR                   233
#define IDC_CBTYPE                      234
#define IDC_LINESIZE                    235
#define IDC_BUTTON4                     236
#define IDC_BUTTON5                     237
#define IDC_CBMARKER                    238
#define IDC_CBAUTOSCALE                 239
#define IDC_MIN                         240
#define IDC_CBTRENDLINEAR               241
#define IDC_RADIO4                      242
#define IDC_RADIO5                      243
#define IDC_SPINLSIZE                   244
#define IDC_BSSTYLE                     245
#define IDC_DATETIMEFORMAT              246
#define IDC_BKCOLOR                     247
#define IDC_CHARTCOLOR                  248
#define IDC_INNERCOLOR                  249
#define IDC_CBSHOWLEGEND                250
#define IDC_MARGINS                     251
#define IDC_CBDOUBLEBUFFER              252
#define IDC_BORDER                      253
#define IDC_CBXAXIS                     253
#define IDC_CBALIGNMENT                 254
#define IDC_CBCURVE                     254
#define IDC_FONT                        255
#define IDC_CBYAXIS                     255
#define IDC_CURVE                       256
#define IDC_CBSNAP                      256
#define IDC_PLACEMENT                   257
#define IDC_TRANSPARENT                 257
#define IDC_CBSHOWMARKERS               258
#define IDC_RADIO8                      259
#define IDC_COMBO1                      260
#define IDC_POSITION                    261
#define IDC_MARKERTYPE                  262
#define IDC_WSIZE                       263
#define IDC_SPINWSIZE                   264
#define IDC_MAVG                        265
#define IDC_LINTREND                    266
#define IDC_CUBTREND                    267
#define IDC_EDIT1                       268
#define IDC_POLYTREND                   268
#define IDC_SPIN1                       269
#define IDC_TIMESTEP                    270
#define IDC_EDIT2                       270
#define IDC_CBTIMESTEPTYPE              271
#define IDC_SPIN2                       271
#define IDC_CBGRIDTYPE                  272
#define IDC_TAB                         273
#define IDC_SPINTOL                     274
#define IDC_TOLERANCE                   275
#define IDM_SELECT                      40000
#define IDM_INSERTLABEL                 40001
#define IDM_ZOOM                        40002
#define IDM_RESET                       40003
#define IDM_PAN                         40004
#define IDM_PROPERTIES                  40005
#define IDM_LABELDOPROP                 40006
#define IDM_PRINT                       40007
#define IDM_MAGNIFIER                   40008
#define IDM_LINEARTREND                 40009
#define IDM_CUBICTREND                  40010
#define IDM_CURSOR                      40011
#define IDM_PARENTCALLBACK				40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2
#define _APS_NEXT_COMMAND_VALUE         0
#define _APS_NEXT_CONTROL_VALUE         276
#define _APS_NEXT_SYMED_VALUE           40111
#endif
#endif
