//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PreView.rc
//
#define IDS_PREVIEW                     1
#define IDB_PREVIEW                     1
#define IDS_PREVIEW_PPG                 2
#define IDS_PREVIEW_PPG_CAPTION         3
#define IDS_NO_CURVE                    4
#define IDS_LEFTBOUNDARY                5
#define IDS_RIGHTBOUNDARY               6
#define IDS_CURVE_ALIASNAME_ER          7
#define IDS_PRINTER_ERROR               8
#define IDS_ITALICBOLD                  9
#define IDS_BOLD                        10
#define IDS_ITALIC                      11
#define IDS_NORMAL                      12
#define IDS_NULL_INPUT                  13
#define IDS_ERROR_DIMENSION             14
#define IDS_ALIASFONT                   15
#define IDS_ZERFONT                     16
#define IDS_DEPTHTHINLINE               17
#define IDS_DEPTHMIDLINE                18
#define IDS_DEPTHBOLDLINE               19
#define IDS_ZERTHINLINE                 20
#define IDS_ZERBOLDLINE                 21
#define IDS_FRAMEFILL                   22
#define IDS_HEADFILL                    23
#define IDS_ZERHEADFILL                 24
#define IDS_DRAWREGIONFILL              25
#define IDS_DEPTHREGIONFILL             26
#define IDS_FRAMELINE                   27
#define IDS_MARGIN_TOO_BIG              28
#define IDS_RESULTFONT                  29
#define IDD_PROPPAGE_PREVIEW            200
#define IDD_MAIN_DIALOG                 201
#define IDC_WELL_LISTCTRL               203
#define IDC_PROJECT_LISTCTRL            204
#define IDC_BROWSE_ALL                  205
#define IDC_RESULTLIST                  206
#define IDC_CURSOR_SIZEWE               207
#define IDC_CURSOR_SELECT               208
#define IDC_CURSOR_CROSS                209
#define IDC_CURSOR_SIZENS               210
#define IDD_PLOT_DEPTH                  212
#define IDD_SET_WIDTH                   213
#define IDD_SET_HEIGHT                  214
#define IDR_POP_MENU                    215
#define CG_IDD_PROGRESS                 218
#define IDI_ICON_SOFT                   220
#define IDD_CURVE_ATTDLD                221
#define IDD_BUSYMESSAGE                 222
#define IDD_CURVE_BASE                  223
#define IDD_PROJECT_BROWSE              224
#define IDI_ICON_DB                     225
#define IDI_ICONWELL                    227
#define IDI_ICONWELLOPEN                228
#define IDI_ICONCURRENTUSER             229
#define IDD_CURVE_PAGE                  232
#define IDD_CURVE_FILL                  233
#define IDD_MIN_FONT                    234
#define IDB_FONTTYPE                    236
#define IDD_TRACK_BASE                  237
#define IDD_LAYER_PAGE                  238
#define IDD_FILL_LIST                   239
#define IDD_LINE_LIST                   240
#define IDD_GRID_PAGE                   241
#define IDR_POP_ADMINMENU               242
#define IDD_PAGE_SETUP                  243
#define IDD_RESULT_PAGE                 244
#define IDD_WELL_BROWSE                 246
#define IDD_IMAGE                       248
#define IDD_IMAGE_BASE                  250
#define CG_IDC_PROGDLG_PROGRESS         443
#define IDC_MESG                        444
#define IDC_VERT_OPAQUE                 1000
#define IDC_HORI_OPAQUE                 1002
#define IDC_EDEP_EDIT                   1003
#define IDC_WAITMSG                     1004
#define CG_IDC_PROGDLG_PERCENT          1005
#define IDC_BUSY                        1006
#define IDC_SDEP_EDIT                   1008
#define IDC_PATTERN_COLOR               1009
#define IDC_PATTERN_STYLE               1011
#define IDC_LEFT_EDIT                   1012
#define IDC_RIGHT_EDIT                  1013
#define IDC_PATTERN_PREVIEW             1013
#define IDC_LINE_ITEM                   1015
#define IDC_PATTERN_SYSTEM              1019
#define IDC_WELLTREE                    1020
#define IDC_PATTERN_LTH                 1020
#define IDC_FILL_ITEM                   1021
#define IDC_GRADIENT                    1035
#define IDC_DEPTH_VALUE_DISVISIBLE      1055
#define IDC_LINEWIDTH_COMBO             1066
#define IDC_LINECOLOR_COMBO             1067
#define IDC_NAME1                       1077
#define IDC_LINE_RADIO                  1078
#define IDC_LOG_RADIO                   1079
#define IDC_WELLNAME                    1080
#define IDC_BROWSE_WELL                 1081
#define IDC_ALIAS_NAME                  1082
#define IDC_SLIDER_SDEP                 1083
#define IDC_SLIDER_EDEP                 1084
#define IDC_SCRIPNAME                   1085
#define IDC_STATIC_DEPTO                1086
#define IDC_STATIC_DEPTO3               1088
#define IDC_BROWSE_WELL2                1089
#define IDC_UNIT                        1090
#define IDC_LR                          1091
#define IDC_NAME                        1092
#define IDC_LR2                         1092
#define IDC_CURVEWIDTH_SPIN             1093
#define IDC_CURVE_WIDTH                 1094
#define IDC_CURVE_COLOR                 1096
#define IDC_CURVE_STYLE                 1097
#define IDC_SCALE_TYPE                  1098
#define IDC_LEFT_VALUE                  1099
#define IDC_RIGHT_VALUE                 1100
#define IDC_SELECT_LIST                 1101
#define ID_DEL                          1102
#define ID_ADD                          1103
#define IDC_SELECT_CURVE                1104
#define IDC_SOURCE_CURVE                1105
#define IDC_UNSELECT_LIST               1106
#define IDC_FILL_PATTERN                1107
#define IDC_FILL_TEXT                   1108
#define IDC_FILL_COLOR                  1109
#define IDC_LEFT_SPACE                  1110
#define IDC_RIGHT_SPACE                 1112
#define IDC_TOP_SPACE                   1113
#define IDC_BOTTOM_SPACE                1114
#define IDC_PAGE_WIDTH                  1115
#define IDC_PAGE_HEIGHT                 1116
#define IDC_HEADTOP_SPACE               1117
#define IDC_HEADBOTTOM_SPACE            1118
#define IDC_LEFT                        1153
#define IDC_RIGHT                       1154
#define IDC_RIGHT2                      1157
#define IDC_DEPTH_TRACK_LEFT            1160
#define IDC_DEPTH_TRACK_RIGHT           1161
#define IDC_DEPTH_TRACK_CENTER          1162
#define IDC_SHOW_DEPTH                  1163
#define IDC_DEPTH_VALUE_LEFT            1164
#define IDC_DEPTH_VALUE_RIGHT           1165
#define IDC_DEPTH_VALUE_CENTER          1166
#define IDC_SHOW_TITLE                  1167
#define IDC_TRACK_SDEP                  1168
#define IDC_TRACK_EDEP                  1169
#define IDC_TRACK_DEPSCAL               1170
#define IDC_SDEP                        1171
#define IDC_EDEP                        1172
#define IDC_WIDTH                       1211
#define IDC_MIN_WIDTH                   1212
#define IDC_HEIGHT                      1214
#define IDC_MAX_HEIGHT                  1215
#define IDC_MIN_HEIGHT                  1216
#define IDC_EBANLE_EDIT                 1221
#define IDC_HEAD_SHOW_FILL              1223
#define IDC_STATIC_SDEP                 1228
#define IDC_STATIC_EDEP                 1229
#define IDC_STATIC_LEFT_SPACE           1235
#define IDC_BROWSE                      1246
#define IDC_STATIC1                     1265
#define IDC_GRID_SPIN_LINENUM           1300
#define IDC_LINE_WIDTH_SPIN             1301
#define IDC_GRID_SPIN_LINEWIDTH         1302
#define IDC_GRID_STATIC_TYPE            1306
#define IDC_GRID_LEFT_VALUE             1307
#define IDC_GRID_RIGHT_VALUE            1308
#define IDC_GRID_VERLINE                1309
#define IDC_PLOT_STDEP                  1311
#define IDC_PLOT_ENDEP                  1312
#define IDC_DEP_SCALE                   1313
#define IDC_LINE_PREVIEW                1313
#define IDC_TRACK_GRID                  1314
#define IDC_FONT                        1315
#define IDC_FOREGROUND                  1316
#define IDC_FONT_SIZE                   1317
#define IDC_ITEM                        1319
#define IDC_FONT_STYLE                  1320
#define IDC_ROTATE                      1321
#define IDC_TEXT                        1322
#define IDC_LINE_COLOR                  1323
#define IDC_HSAMPRECT                   1324
#define IDC_VSAMPRECT                   1325
#define IDC_GRID_LOG_TYPE               1326
#define IDC_GRID_LINENUM                1327
#define IDC_GRID_LINE_TYPE              1328
#define IDC_GRID_LINE_WIDTH             1329
#define IDC_GRID_LINE_COLOR             1330
#define IDC_GRID_HORLINE                1331
#define IDC_GRID_SELECT_ITEM            1332
#define IDC_LINE_STYLE                  1333
#define IDC_LINE_WIDTH                  1334
#define IDC_GRID_DIP_TYPE               1335
#define IDC_GRID                        1342
#define IDC_CHECK1                      1356
#define IDC_TRACKRESIZE                 1358
#define IDC_RADIO1                      1361
#define IDC_RADIO2                      1365
#define IDC_RADIO3                      1368
#define IDC_RADIO4                      1372
#define IDC_RADIO5                      1375
#define IDC_HOR_SCALE                   1378
#define IDC_BIT                         1380
#define IDC_COMBO_CRMOLDL               1388
#define IDC_COMBO1                      1389
#define IDC_FILENAME                    1390
#define IDC_EDIT_ANGLE                  1401
#define IDC_SPIN1                       1402
#define IDC_PREVIEW                     1407
#define IDC_CHECK2                      1412
#define IDC_COMBO2                      1413
#define IDC_FILTERNUM                   1416
#define IDC_COLORGRADE                  1417
#define IDC_BKCOLOR                     1419
#define ID_SET_DEPTH                    32770
#define ID_OBJECT_PROPTERTIES           32772
#define ID_DOCDATA_UPDATE               32777
#define ID_MATCH_ALLOBJECT              32779
#define ID_ADD_CURVE                    32781
#define ID_ADD_TRACK                    32782
#define ID_SETUP_PAGE                   32784
#define ID_FILE_SAVE_BMP                32871
#define ID_FILE_SAVE_DATA               32872
#define ID_CURVE_VALUE                  33029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        251
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         207
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
