//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageMan.rc
//
#define IDR_LOGPLTTYPE_SRVR_IP          4
#define IDR_LOGPLTTYPE_SRVR_EMB         5
#define IDR_LOGPLTTYPE_CNTR_IP          6
#define IDM_DLGBMP_CLIPBOARD            0x0010
#define IDM_HOLE_KEYSEAT                0x0011
#define IDM_HOLE_BREAKOUT               0x0012
#define IDM_HOLE_SLIP                   0x0013
#define IDM_HOLE_CLEAR                  0x0014
#define IDM_HOLE_SCALE                  0x0015
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDP_FAILED_TO_CREATE            102
#define IDB_SPLASH                      103
#define ID_INDICATOR_DATE               104
#define ID_INDICATOR_TIME               105
#define IDD_CURVE_EDIT                  107
#define IDR_MAINFRAME                   128
#define IDR_LOGPLTTYPE                  129
#define IDD_TEXT_LIST                   137
#define IDD_CURVE_PAGE                  140
#define IDD_CURVE_FILL                  141
#define IDD_AZIM_FREQ                   144
#define IDD_DANG_FREQ                   145
#define IDD_FID_BASE                    146
#define IDD_DIP_BASE                    146
#define IDD_DIP_PAGE                    147
#define IDD_DEVDAZ                      148
#define IDD_WAVE                        149
#define IDD_WAVE_BASE                   150
#define IDD_CURVE_BASE                  151
#define IDD_PAGE_SETUP                  153
#define IDD_VIEW_GRID                   154
#define IDD_DOC_ALIGN                   155
#define IDD_DOC_VERT_ALIGN              156
#define IDB_HOTTOOLBARSM                156
#define IDD_TRACK_ARRANGLE              157
#define IDD_ALIGN_DEPTH                 158
#define IDR_POPUP_OTHER_MENU            160
#define IDD_TEXT_ALIGN                  161
#define IDD_TRACK_BASE                  162
#define IDR_POPUP_CURVE_MENU            163
#define IDD_SET_WIDTH                   164
#define IDD_SET_HEIGHT                  165
#define IDD_DOC_HORI_ARRANGLE           167
#define IDR_ARRANGLETOOL                168
#define IDD_RESULT_PAGE                 171
#define IDD_PRINT_DLG                   172
#define IDD_TEXTFILE_PAGE               173
#define IDD_RESULTLIST_PAGE             173
#define IDD_CURVE_DEP                   174
#define IDD_WAVE_DEP                    175
#define IDR_PLOTTOOL                    177
#define IDC_SELECT                      180
#define IDC_CURSOR_CROSS                194
#define IDC_CURSOR_ARROW                195
#define IDC_CURSOR_SIZENS               196
#define IDC_CURSOR_SIZEWE               197
#define IDD_CURVE_FILTER                218
#define IDD_CURVE_UNITE                 219
#define IDD_CURVE_STAT                  220
#define IDB_EMPTY                       221
#define IDC_CURSOR1                     226
#define IDB_BITMAP2                     229
#define IDB_BITMAP3                     234
#define IDD_CURVE_PLUS                  361
#define IDD_CORE_DATA_PRO               362
#define IDB_BITMAP4                     363
#define IDD_CUSTOM_FILEOPEN             364
#define IDD_BMPSAVEDLG                  366
#define IDD_SCALEFACTOR                 367
#define IDD_INPUTBOX                    369
#define IDD_DATAPROCESS                 370
#define IDD_EVALUATE_DIALOG             370
#define IDD_CURVE_BASELINE              377
#define IDD_CURVEDEP_PLUS               378
#define IDD_LINE_LOG                    379
#define IDD_REMARK                      381
#define IDD_SETREMARK                   383
#define IDD_PARA_SET                    384
#define IDC_CURSOR_BOX                  385
#define IDC_CURSOR_HANDWRITE            386
#define IDD_SELECT_CURVE                388
#define IDB_BITMAP5                     389
#define IDB_BITMAP6                     390
#define IDR_HORLINE_MENU                391
#define IDD_LAYER                       392
#define IDD_LAYER_PAGE                  395
#define IDR_POP_SCALE                   401
#define IDD_FREQ_BASE                   403
#define IDD_DEV_BASE                    404
#define IDR_POPUP_PAGE_MENU             405
#define IDD_CURVE3D                     406
#define IDD_CURVE3D_BASE                407
#define IDB_TOOLBAR_HOT                 408
#define IDD_COMPARABILITY_DIALOG        409
#define IDD_WAVE_SHOWDLG                412
#define IDB_PLOTBAR_HOT                 413
#define IDD_STAT_STANDARD               415
#define IDD_COMPUTE_ENERGY              417
#define IDD_IMAGE                       419
#define IDD_IMAGE3D                     420
#define IDD_IMAGE3D_BASE                421
#define IDD_IMAGE_BASE                  422
#define IDD_STRATUM_PAGE                425
#define IDD_HANDWORK_PAGE               428
#define IDD_MARKVECTOR_PAGE             429
#define IDD_MARK_CORREPARA              433
#define IDD_IMG_FREQUENCY               440
#define IDD_MARKAZI_PAGE                441
#define IDD_MARKDIP_PAGE                442
#define IDD_IMAGECURVE_BASE             443
#define IDD_IMAGECURVE_PAGE             444
#define IDD_ACIMAGEPREP_DIALOG          445
#define IDD_ECHO                        450
#define IDD_ECHO_BASE                   451
#define IDD_CCL_BASE                    453
#define IDD_CCL_FILL                    454
#define IDD_CCL_PAGE                    455
#define IDD_POLE_PAGE                   456
#define IDD_HOLE_ANALYSIS               457
#define IDD_MULTCURVE_DEP               458
#define IDD_DIPCOMPUTE_DIALOG           462
#define IDD_MODIFY_HANDWORK_DLG         463
#define IDD_DIALOG1                     465
#define IDD_ARRAYWAVE                   465
#define IDD_ARRAYWAVE_BASE              466
#define IDD_CONTOUR_PARA                467
#define IDD_CONTOUR_STATPARA            468
#define IDD_SINCONTOUR_PARA             469
#define IDD_CONTOUR_SINPARA             469
#define IDD_CONTOUR_SINSTATPARA         470
#define IDC_STATIC_TODO                 471
#define IDC_TRACK_SELECT                472
#define IDC_HORIFID_HORI_ARRANGLE_LEFT  473
#define IDC_PROGRESS1                   474
#define IDC_HORIFID_HORI_ARRANGLE_RIGHT 475
#define IDC_CURVENAME                   476
#define IDC_PROGRESS2                   477
#define IDC_HORIFID_HORI_ARRANGLE_LR    478
#define IDC_COMBO_SERIES                479
#define IDC_HORIFID_HORI_ARRANGLE_NONE  480
#define IDC_START                       481
#define IDC_CHECK_ACCELERATE            482
#define IDC_END                         483
#define IDC_STAT_THICK                  484
#define IDC_CHECK_BUTTON                485
#define IDC_HORIFID_HORI_ALIGN_RIGHT    486
#define IDC_CHECK_PAD                   487
#define IDC_HORIFID_HORI_ALIGN_LR       488
#define IDC_SUBWAVE                     489
#define IDC_HOTIFID_HORI_ALIGN_NONE     490
#define IDC_START_WIN                   491
#define IDC_BUTTON1                     492
#define IDC_EDIT_BITS                   493
#define IDC_HORIFID_VERT_ARRANGLE_TOP   494
#define IDC_START_DEP                   495
#define IDC_HORIFID_VERT_ARRANGLE_BOTTOM 496
#define IDC_START_WIN2                  497
#define IDC_COMBO_FILTER                498
#define IDC_HORIFID_VERT_ARRANGLE_TP    499
#define IDC_END_WIN                     500
#define IDC_BUTTON2                     501
#define IDC_CHECK_AZIMUTH               502
#define IDC_HORIFID_VERT_ARRANGLE_NONE  503
#define IDC_END_DEP                     504
#define IDC_PROSTDEP                    505
#define IDC_HORIFID_VERT_ALIGN_TOP      506
#define IDC_END_WIN2                    507
#define IDC_PROENDEP                    508
#define IDC_HORIFID_VERT_ALIGN_BOTTOM   509
#define IDC_BUTTON3                     510
#define IDC_RLEV                        511
#define IDC_HORIFID_VERT_ALIGN_TP       512
#define IDC_HORIFID_VERT_ALIGN_NONE     513
#define IDC_VERTIFID_HORI_ARRANGLE_LEFT 514
#define IDC_VERTFID_HORI_ARRANGLE_RIGHT 515
#define IDC_VERTFID_HORI_ARRANGLE_LR    516
#define IDC_VERTIFID_HORI_ARRANGLE_NONE 517
#define IDC_VERTFID_VERT_ALIGN_TOP      518
#define IDC_STAT_FILL_SIGN1             519
#define IDC_VERTFID_VERT_ALIGN_BOTTOM   520
#define IDC_VERTFID_VERT_ALIGN_TP       521
#define IDC_VERTFID_VERT_ALIGN_NONE     522
#define IDC_TRACK_HORI_ARRANGLE_LEFT    523
#define IDC_TEXTLIST                    524
#define IDC_DATASTAT                    525
#define IDC_TRACK_HORI_ARRANGLE_RIGHT   526
#define IDC_TRACKF_HORI_ARRANGLE_LR     527
#define IDC_STAT_FILL_SIGN2             528
#define IDC_TRACK_HORI_ARRANGLE_NONE    529
#define IDC_STAT_FILL_SIGN3             530
#define IDC_STAT_FILL_SIGN4             531
#define IDC_STAT_FILL_SIGN5             532
#define IDC_WIN_LENGTH                  533
#define IDC_BUTTON4                     534
#define IDC_SEARCH_LENGTH               535
#define IDC_BUTTON5                     536
#define IDC_STEP_LENGTH                 537
#define IDC_MIN_COEF                    538
#define IDC_GRADIENT                    539
#define IDC_MAX_DIP                     540
#define IDC_ALIGN_TOP                   541
#define IDC_MIN_COEF2                   542
#define IDC_ALIGN_HEAD                  543
#define IDC_CURVE_LIST                  544
#define IDC_MIN_COEF3                   545
#define IDC_COMBO_RMFNAME               546
#define IDC_RMFWELL                     547
#define IDD_CREATESPECT_DLG             871
#define IDD_SCALE_DLG                   872
#define IDD_FREQUENCY_DIALOG            873
#define IDD_DIALOG2                     874
#define IDD_CROSS_DIALOG                874
#define IDD_CREATEIMAGELIST             876
#define IDI_ICON1                       877
#define IDC_STATIC_MAX                  1048
#define IDC_STATIC_MAX2                 1049
#define IDC_PIE_WIDTH                   1050
#define IDC_PIE_COLOR                   1051
#define IDC_PIE_NUM                     1052
#define IDC_PIE_PREVIEW                 1053
#define IDC_DEPTH_LEVEL                 1054
#define IDC_CIRCLE_WIDTH                1055
#define IDC_CIRCLE_COLOR                1056
#define IDC_CIRCLE_RADIUS               1057
#define IDC_TAIL_LENGTH                 1058
#define IDC_TAIL_WIDTH                  1059
#define IDC_TAIL_COLOR                  1060
#define IDC_DIP_PREVIEW                 1061
#define IDC_HORI_WIDTH                  1062
#define IDC_HORI_LENGTH                 1063
#define IDC_HORI_COLOR                  1064
#define IDC_VERT_WIDTH                  1065
#define IDC_VERT_HEIGHT                 1066
#define IDC_VERT_COLOR                  1067
#define IDC_VERT_NUM                    1068
#define IDC_EDIT18                      1068
#define IDC_WELLNAME                    1069
#define IDC_BROWSE_WELL                 1070
#define IDC_ALIAS_NAME                  1071
#define IDC_EDIT20                      1071
#define IDC_SLIDER_SDEP                 1072
#define IDC_SLIDER_EDEP                 1073
#define IDC_EDIT21                      1073
#define IDC_STATIC_DEPTH                1074
#define IDC_EDIT19                      1074
#define IDC_STATIC_DEPTO                1075
#define IDC_NAME1                       1076
#define IDC_STATIC_DEPTH2               1077
#define IDC_NAME3                       1078
#define IDC_STATIC_DEPTO2               1079
#define IDC_STATIC_DEPTO3               1080
#define IDC_STATIC_MAX3                 1080
#define IDC_STATIC_DEPTO5               1081
#define IDC_CURVE_STYLE                 1082
#define IDC_NAME5                       1083
#define IDC_STATIC_MAX5                 1083
#define IDC_SPIN_LEVEL                  1084
#define IDC_UNIT                        1090
#define IDC_LR                          1091
#define IDC_NAME                        1092
#define IDC_CURVEWIDTH_SPIN             1093
#define IDC_NAME2                       1093
#define IDC_CURVE_WIDTH                 1094
#define IDC_NAME4                       1094
#define IDC_FACTOR                      1095
#define IDC_CURVE_COLOR                 1096
#define IDC_CURVE_COLOR2                1097
#define IDC_SCALE_TYPE                  1098
#define IDC_LEFT_VALUE                  1099
#define IDC_RIGHT_VALUE                 1100
#define IDC_SELECT_LIST                 1101
#define ID_DEL                          1102
#define ID_ADD                          1103
#define IDC_SELECT_CURVE                1104
#define IDC_SOURCE_CURVE                1105
#define IDC_UNSELECT_LIST               1106
#define IDC_FILL_PATTERN                1107
#define IDC_FILL_TEXT                   1108
#define IDC_FILL_COLOR                  1109
#define IDC_LEFT_SPACE                  1110
#define IDC_RIGHT_SPACE                 1112
#define IDC_TOP_SPACE                   1113
#define IDC_BOTTOM_SPACE                1114
#define IDC_PAGE_WIDTH                  1115
#define IDC_PAGE_HEIGHT                 1116
#define IDC_HEADTOP_SPACE               1117
#define IDC_HEADBOTTOM_SPACE            1118
#define IDC_XGRID                       1120
#define IDC_YGRID                       1121
#define IDC_WAVE_COLOR1                 1127
#define IDC_TEXT_ALIGN_LEFT             1128
#define IDC_TEXT_HORIALIGN_LEFT         1129
#define IDC_TEXT_ALIGN_RIGHT            1130
#define IDC_TEXT_HORIALIGN_RIGHT        1131
#define IDC_TEXT_ALIGN_CENTER           1132
#define IDC_CLIP_TEXT                   1133
#define IDC_TEXT_VERTALIGN_TOP          1134
#define IDC_TEXT_VERTALIGN_BOTTOM       1135
#define IDC_TEXT_VERTALIGN_CENTER       1136
#define IDC_TEXT_ROTATE                 1137
#define IDC_WAVE                        1140
#define IDC_DEN                         1141
#define IDC_FILL_WAVE                   1142
#define IDC_WAVE_COLOR                  1143
#define IDC_SPIN_AMP                    1144
#define IDC_FILL_WAVE2                  1145
#define IDC_LEVEL                       1146
#define IDC_PLOTAMP                     1147
#define IDC_WF1                         1148
#define IDC_WAVE_COLOR0                 1148
#define IDC_WF2                         1149
#define IDC_WF3                         1150
#define IDC_WF4                         1151
#define IDC_WFAMP                       1152
#define IDC_LEFT                        1153
#define IDC_RIGHT                       1154
#define IDC_HORIFID_HORI_ALIGN_LEFT     1155
#define IDC_DEPTH_TRACK_LEFT            1160
#define IDC_DEPTH_TRACK_RIGHT           1161
#define IDC_DEPTH_TRACK_CENTER          1162
#define IDC_SHOW_DEPTH                  1163
#define IDC_DEPTH_VALUE_LEFT            1164
#define IDC_DEPTH_VALUE_RIGHT           1165
#define IDC_DEPTH_VALUE_CENTER          1166
#define IDC_SHOW_TITLE                  1167
#define IDC_TRACK_SDEP                  1168
#define IDC_TRACK_EDEP                  1169
#define IDC_SDEP                        1171
#define IDC_EDEP                        1172
#define IDC_WIDTH                       1211
#define IDC_MIN_WIDTH                   1212
#define IDC_MAX_WIDTH                   1213
#define IDC_HEIGHT                      1214
#define IDC_MAX_HEIGHT                  1215
#define IDC_MIN_HEIGHT                  1216
#define IDC_CURVE_TYPE                  1219
#define IDC_EBANLE_EDIT                 1221
#define IDC_LTH_CUTVE                   1222
#define IDC_HEAD_SHOW_FILL              1223
#define IDH_DOC_HORI_ARRANGLE           1224
#define IDH_DOC_VERT_ALIGN              1227
#define IDC_STATIC_SDEP                 1228
#define IDC_STATIC_EDEP                 1229
#define IDH_SET_HEIGHT                  1230
#define IDH_SET_WIDTH                   1231
#define IDH_PAGE_SETUP                  1232
#define IDC_STATIC_LEFT_SPACE           1235
#define IDC_MIN_DANG                    1236
#define IDC_MAX_DANG                    1237
#define IDC_DEPLEVEL                    1239
#define IDC_DRIVES                      1241
#define IDC_DEV_LEFT_VAL                1244
#define IDC_DEV_RIGHT_VAL               1245
#define IDC_PLOT_HEAD                   1245
#define IDC_PLOT_TOP_REM                1246
#define IDC_PLOT_BOTTOM_REM             1247
#define IDC_RESERVE_SPACE               1248
#define IDC_MAX_PAGESIZE                1249
#define IDC_PLOT_TEXTFILE               1250
#define IDC_PLOT_RESULTLIST             1250
#define IDC_PRINT                       1252
#define IDC_PLOT_TRACK                  1253
#define IDC_TEXTFILE_TOP_SPACE          1254
#define IDC_RESULTLIST_TOP_SPACE        1254
#define IDC_EDIT10                      1330
#define IDC_GUAGE                       1331
#define IDC_IMAGE                       1332
#define IDC_PATH                        1333
#define IDC_CENTER                      1334
#define IDC_FILEICON                    1335
#define IDC_STRETCH                     1336
#define IDC_YELLOW_BLACK3               1339
#define IDC_EDIT_INPUT                  1340
#define IDC_DEP                         1341
#define IDC_EDIT_E_OLD                  1342
#define IDC_EDIT_M_OLD                  1343
#define IDC_EDIT_S_OLD                  1344
#define IDC_EDIT_E_NEW                  1345
#define IDC_EDIT_M_NEW                  1346
#define IDC_EDIT_RIGHT                  1346
#define IDC_EDIT_S_NEW                  1347
#define IDC_STATIC_CURVENAME            1348
#define IDC_EDIT_DEPNEWVALUE            1349
#define IDC_STARTIME                    1350
#define IDC_NOGRAY                      1351
#define IDC_GRAY                        1352
#define IDC_GRID                        1353
#define IDC_TOTALLGRID                  1354
#define IDC_LAYERGRID                   1355
#define IDC_STATICTOTALL                1356
#define IDC_STATICLAYER                 1357
#define IDC_RADIO6                      1358
#define IDC_RADIO7                      1359
#define IDC_COMPUTECOEF                 1361
#define IDC_POINT1DEP                   1362
#define IDC_POINT1VALUE                 1363
#define IDC_POINT2DEP                   1364
#define IDC_BASEMULTI_FACTOR            1365
#define IDC_BASEPLUS_FACTOR             1366
#define IDC_BASEPOINT1DEP               1367
#define IDC_BASEPOINT1VALUE             1368
#define IDC_BASEPOINT2DEP               1369
#define IDC_BASEPOINT2VALUE             1370
#define IDC_BASECOMPUTECOEF             1371
#define IDC_BASE_DEP                    1372
#define IDC_COLOR_GRADE                 1373
#define IDC_SPACE                       1374
#define IDC_LEFT_SCAL1                  1375
#define IDC_RIGHT_SCAL1                 1376
#define IDC_COLORGRADE                  1451
#define IDC_BKCOLOR                     1452
#define IDC_TYPESIN1                    1453
#define IDC_TYPESIN2                    1454
#define IDC_TYPESIN3                    1455
#define IDC_TYPESIN4                    1456
#define IDC_TYPESIN5                    1457
#define IDC_TYPESIN6                    1458
#define IDC_CHECK12                     1459
#define ID_SET_CONTOUR_PARA             1460
#define IDC_DATA_MESSAGE                1461
#define ID_DEL_RECTANGLE                1462
#define ID_GET_RECTANGL_CONTOUR         1466
#define ID_BOX_ANISYS                   1467
#define ID_OPEN_CONTOUR                 1468
#define ID_SAVE_CONTOUR                 1469
#define ID_SAVEAS_CONTOUR               1470
#define ID_PICKUP_STAT                  1471
#define ID_PICKUP_LIST                  1473
#define ID_SIN_CONTOUR                  1476
#define ID_PICKUP_SINSTAT               1478
#define ID_PICKUP_SINLIST               1480
#define ID_CREATE_SINLIST               1482
#define ID_SETHOLE_STATPARA             1484
#define ID_SETCRACK_STATPARA            1486
#define ID_DRAWCONNECTION               1490
#define ID_DEL_ALLHOLE                  1491
#define ID_Menu                         1492
#define ID_PERSISTRESULT                1493
#define ID_BUTTON1497                   1497
#define ID_GET_ELLIPSE                  1498
#define ID_GET_ELLIPSE_CONTOUR          1499
#define IDC_TEXTFILE_NAME               1500
#define IDC_TEXTFILE_DATA               1501
#define IDC_RESULTLIST_DATA             1502
#define IDC_TEXTFILE_PROMPT             1503
#define IDC_TEXTFILE_NOTE               1504
#define IDC_RESULTLIST_NOTE             1505
#define IDC_BROWSE                      1506
#define IDC_TEXTFILE_LEFT_SPACE         1507
#define IDC_RESULTLIST_LEFT_SPACE       1508
#define IDC_STATIC_DEP                  1509
#define IDC_MOVEDEP                     1510
#define IDC_DEPPOINT                    1511
#define IDC_EXTENDDEP                   1512
#define IDC_NICETYDEPPOINT              1513
#define IDC_EDIT1                       1514
#define IDC_EDITDATA                    1515
#define IDC_EDIT_STANDARD               1516
#define IDC_EDIT_STANDARD1              1517
#define IDC_RESULTDATA                  1518
#define IDC_TEXTFILE_REM_HIGHT          1519
#define IDC_RESULTLIST_REM_HIGHT        1520
#define IDC_REVISEDEP_OK                1521
#define IDC_EDIT7                       1522
#define IDC_REVISEDEP_CANCEL            1523
#define IDC_EDIT11                      1524
#define IDC_REVISEWAVEDEP_OK            1525
#define IDC_EDIT_STANDARD2              1526
#define IDC_EDIT12                      1527
#define IDC_REVISEWAVEDEP_CANCEL        1528
#define IDC_EDIT_STANDARD3              1529
#define IDC_EDIT13                      1530
#define IDC_EDIT_STANDARD4              1531
#define IDC_EDIT14                      1532
#define IDC_DATAEDIT_OK                 1533
#define IDC_EDIT_STANDARD5              1534
#define IDC_DATAEDIT_CANCEL             1535
#define IDC_DATAFILTER_OK               1536
#define IDC_DATAFILTER_CANCEL           1537
#define IDC_FILTER3                     1538
#define IDC_FILTER5                     1539
#define IDC_StartDep                    1540
#define IDC_EndDep                      1541
#define IDC_UpdateDep                   1542
#define IDC_STATICSdep                  1543
#define IDC_STATICEdep                  1544
#define IDC_EDIT_SDEP                   1545
#define IDC_EDIT_EDEP                   1546
#define IDC_EDIT_RESULT                 1547
#define IDC_EDIT_RESULT1                1548
#define IDC_EDIT_RESULT2                1549
#define IDC_EDIT_RESULT3                1550
#define IDC_EDIT_RESULT4                1551
#define IDC_EDIT_RESULT5                1552
#define IDC_DATASTAT_OK                 1553
#define IDC_DATASTAT_CANCEL             1554
#define IDC_EDIT_MAX                    1555
#define IDC_STATIC1                     1556
#define IDC_EDIT_MINVALUE               1557
#define IDC_EDIT_MIN                    1558
#define IDC_STATIC2                     1559
#define IDC_EDIT_MAXVALUE               1560
#define IDC_BROWS                       1561
#define IDC_CHECK1                      1562
#define IDC_TRACKRESIZE                 1563
#define IDC_CHECK_E                     1564
#define IDC_PREVERGE                    1565
#define IDC_PREFIX                      1566
#define IDC_BASEPREVERGE                1567
#define IDC_RADIO1                      1568
#define IDC_CHECK_S                     1569
#define IDC_CHECK6                      1570
#define IDC_RADIO2                      1571
#define IDC_CHECK_M                     1572
#define IDC_CHECK7                      1573
#define IDC_RADIO3                      1574
#define IDC_CHECK_DEP                   1575
#define IDC_CHECK8                      1576
#define IDC_RADIO4                      1577
#define IDC_CHECK9                      1578
#define IDC_RADIO5                      1579
#define IDC_CHECK5                      1580
#define IDC_CHECK10                     1581
#define ID_CURVEUNITE_OK                1582
#define IDC_CHECK11                     1583
#define ID_CURVEUNITE_CANCEL            1584
#define IDC_STATIC_NAME                 1585
#define IDC_EXEDEP                      1586
#define IDC_EXSDEP                      1587
#define IDC_PLUS_FACTOR                 1588
#define IDC_MULTI_FACTOR                1589
#define IDC_DATAPLUS_OK                 1590
#define IDC_DATAPLUS_CANCEL             1591
#define IDC_EDIT2                       1592
#define IDC_FILENAME                    1593
#define IDC_EDIT17                      1593
#define IDC_EDIT3                       1594
#define IDC_STARTPOS                    1595
#define IDC_EDIT4                       1596
#define IDC_RESULT_SDEP                 1597
#define IDC_EDIT5                       1598
#define IDC_RESULT_EDEP                 1599
#define IDC_EDIT6                       1600
#define IDC_EDIT8                       1601
#define IDC_CORE_SIGN                   1602
#define IDC_OPEN_TEXT_FILE              1603
#define IDC_STAT_FILL_SIGN              1604
#define IDC_EDIT9                       1605
#define IDC_OK                          1606
#define IDC_YELLOW_BLACK2               1607
#define IDC_YELLOW_BLACK                1608
#define IDC_BASENAME                    1609
#define IDC_POINT2VALUE                 1610
#define IDC_FILL_IMAGE                  1611
#define IDC_COLOR_GRADE2                1612
#define IDC_DAZ                         1613
#define IDC_HEAD_STYLE                  1614
#define IDC_POLE_ARRAY                  1650
#define IDC_SCAL_MODE1                  1651
#define IDC_LEFT_SCAL2                  1652
#define IDC_RIGHT_SCAL2                 1653
#define IDC_DIPGRAD                     1654
#define IDC_SCAL_MODE2                  1655
#define IDC_STANDARD                    1656
#define IDC_CURVE_NAME                  1657
#define IDC_HOR_SCALE                   1658
#define IDC_CURVE_DEP_RANGE             1659
#define IDC_BIT                         1660
#define IDC_DELAY_CURVE                 1661
#define IDC_RESULTGRID                  1662
#define IDC_DELAY_CURVENO               1663
#define IDC_DOUBLE_DEN                  1664
#define IDC_PLUS_CURVE                  1665
#define IDC_WAVE_WIDTH                  1666
#define IDC_COMBO_CRMOLDL               1667
#define IDC_COMBO1                      1668
#define IDC_DELROW                      1669
#define IDC_COLOR_GRAD                  1670
#define IDC_WAVENAME                    1670
#define IDC_INSERTROW                   1671
#define IDC_CHECK2                      1671
#define IDC_ADDROW                      1672
#define IDC_CHECK3                      1672
#define IDC_COMBO2                      1673
#define IDC_CHECK4                      1673
#define IDC_DELCOL                      1674
#define IDC_COMBO3                      1674
#define IDC_CHART                       1675
#define IDC_COMBO4                      1675
#define IDC_FILTERNUM                   1676
#define IDC_COMBO5                      1676
#define IDC_EOCH_COLOR                  1677
#define IDC_CHECK_CLEARBUF              1677
#define IDC_EOCH_COLOR2                 1678
#define IDC_CHECK_BALANCE               1678
#define IDC_HIGH_VALUE                  1679
#define IDC_STATIC_WELL                 1679
#define IDC_LOW_VALUE                   1680
#define IDC_CHECK_COPYDATA              1680
#define IDC_SPIN1                       1681
#define IDC_CHECK_UNITDATA              1681
#define IDC_SPIN2                       1682
#define IDC_CHECK_GRDEP                 1682
#define IDC_SPIN3                       1683
#define IDC_CHECK_RESAMPLEAZI           1683
#define IDC_SPIN4                       1684
#define IDC_CHECK_CREATRADS             1684
#define IDC_SPIN5                       1685
#define IDC_CHECK_GEOMETRY              1685
#define IDC_PREVIEW                     1686
#define IDC_CHECK_STASCALE              1686
#define IDC_LISTBOX                     1687
#define IDC_CHECK_DYNSCALE              1687
#define IDC_LIST1                       1688
#define IDC_EDIT_WINLONGTH              1688
#define IDC_ARRANG                      1689
#define IDC_CHECK_GRADS                 1689
#define IDC_SET_STAT_STANDARD           1690
#define IDC_CHECK_EXP                   1690
#define IDC_COMPOSITOR                  1691
#define IDC_TAB1                        1691
#define IDC_SCALE_DEP                   1692
#define IDC_BASE_FRM                    1692
#define IDC_PLUS_CURVENO                1693
#define IDC_COMBO_NAME                  1693
#define IDC_VDL_RUN                     1694
#define IDC_DOUBLE_DEN2                 1695
#define IDC_ENERGY_RUN                  1696
#define IDC_TIME2NAME                   1697
#define IDC_EN_WIDTH                    1697
#define IDC_PROGRESS3                   1699
#define ID_CREATE_FULLIMAGE             1802
#define ID_CREATE_IMAGE3D               1804
#define ID_POR_COMPUTE                  1807
#define ID_RMF_SCALE                    1809
#define ID_DRAW_FREQUENCY               1811
#define ID_DRAW_CROSS                   1812
#define ID_CREATE_HPOR                  1814
#define ID_DRAW_DIAMETER                1816
#define ID_DRAW_POR                     1818
#define ID_IMAGE_ANALYSIS               1819
#define ID_CREATEIMAGELIST              1821
#define IDC_EDIT15                      1861
#define IDC_EDIT16                      1862
#define IDC_STATIC_MSG                  1862
#define IDC_EDIT_LEFT                   1863
#define IDS_DEVDAZPROPERTIES            5968
#define IDS_SIZE                        5969
#define IDS_DRAGLINE                    5970
#define IDS_CHANGELINE                  5971
#define IDS_ADDPOINT                    5972
#define IDS_EDITPOINT                   5973
#define IDS_NUMBER                      5974
#define IDC_DEL_ROW                     5975
#define IDC_INSERT_ROW                  5976
#define ID_CANCEL_EDIT_CNTR             32724
#define ID_CANCEL_EDIT_SRVR             32725
#define ID_SET_DEPTHSCALE               32800
#define ID_SET_DEPTH                    32801
#define ID_OBJECT_MOVETOFRONT           32810
#define ID_OBJECT_MOVETOBACK            32811
#define ID_OBJECT_MOVEFORWARD           32812
#define ID_OBJECT_MOVEBACK              32813
#define ID_OBJECT_PROPTERTIES           32814
#define ID_VIEW_PAPERCOLOR              32820
#define ID_VIEW_PLOTBAR                 32821
#define ID_VIEW_GRID                    32822
#define ID_SET_VIEW_GRID                32823
#define ID_TRACK_ARRANGLE_HELP          32831
#define ID_DRAW_SELECT                  32840
#define ID_DRAW_LINE                    32841
#define ID_DRAW_RECT                    32842
#define ID_DRAW_ROUNDRECT               32843
#define ID_DRAW_POLYGON                 32844
#define ID_DRAW_ELLIPSE                 32845
#define ID_DRAW_TEXT                    32846
#define ID_LINEARC                      32847
#define ID_RECT_ARROW                   32848
#define ID_ELLIPSE_ARROW                32849
#define ID_OBJECT_LINK                  32850
#define ID_OBJECT_UNLINK                32851
#define ID_EDIT_POLY                    32852
#define ID_ADD_TRACK                    32860
#define ID_ADD_CURVE                    32861
#define ID_ADD_RESULT                   32862
#define ID_ADD_CORE                     32863
#define ID_ADD_LTH                      32864
#define ID_ADD_DANGDDIR                 32865
#define ID_ADD_DEVDAZ                   32867
#define ID_ADD_AZIMFREQ                 32868
#define ID_ADD_SCHMIDT                  32869
#define ID_ADD_SERIA                    32870
#define ID_ADD_FAST                     32871
#define ID_ADD_WELLHOLE                 32872
#define ID_WF1                          32873
#define ID_WF2                          32874
#define ID_WF3                          32875
#define ID_WF4                          32876
#define ID_EDIT_ENABLE                  32880
#define ID_HEAD_ALL                     32882
#define ID_ALIGN_GRID                   32884
#define ID_TEMPLATE                     32890
#define ID_SETUP_PAGE                   32891
#define ID_SAVE_AS_TEMPLATE             32892
#define ID_TEXT_ALIGN_LEFT              32900
#define ID_TEXT_ALIGN_RIGHT             32901
#define ID_VIEW_PAPER_COLOR             32902
#define ID_TEXT_ALIGN_CENTER            32903
#define ID_SYMBOL_CORE                  32904
#define ID_SYMBOL_LTH                   32905
#define ID_SYMBOL_RESULT                32906
#define ID_SYMBOL_USER                  32907
#define ID_SYMBOL_PROGMAN_CORE          32909
#define ID_SYMBOL_PROGMAN_LTH           32912
#define ID_SYMBOL_PROGMAN_RESULT        32913
#define ID_SYMBOL_PROGMAN_USER          32914
#define ID_VERT_ARRANGLE_TOP            32923
#define ID_VERT_ARRANGLE_BOTTOM         32924
#define ID_VERT_ARRANGLE_JUST           32925
#define ID_VERT_ARRANGLE_NONE           32926
#define ID_HORI_ARRANGLE_LEFT           32928
#define ID_HORI_ARRANGLE_RIGHT          32929
#define ID_HORI_ARRANGLE_JUST           32930
#define ID_HORI_SET_FULL                32931
#define ID_HORI_ARRANGLE_NONE           32932
#define ID_SET_HEIGHT                   32934
#define ID_SET_WIDTH                    32937
#define ID_VERT_ALIGN_NONE              32941
#define ID_VERT_ALIGN_JUST              32942
#define ID_VERT_ALIGN_BOTTOM            32943
#define ID_VERT_ALIGN_TOP               32944
#define ID_HORI_ALIGN_LEFT              32945
#define ID_HORI_ALIGN_RIGHT             32946
#define ID_HORI_ALIGN_JUST              32947
#define ID_HORI_ALIGN_NONE              32948
#define ID_HORI_ALIGN_LR                32949
#define ID_VERT_ALIGN_TB                32950
#define ID_VERT_SET_FULL                32951
#define ID_VIEW_ARRANGLEBAR             32952
#define ID_DEPTH_UNIT                   32953
#define ID_DEPTH_UNIT_M                 32954
#define ID_DEPTH_UNIT_FEET              32955
#define ID_SCALE_LIST                   32956
#define ID_PLOTFIDHEAD                  32957
#define ID_TEXT_FILE                    32958
#define ID_ADD_TEXT_FILE                32959
#define ID_TRACK_AUTOARRANGLE           32960
#define ID_TRACK_SETAUTOARRANGLE        32961
#define ID_TRACK_ARRANGLE               32962
#define ID_TRACK_HORIFID_ALIGN_LEFT     32963
#define ID_TRACK_HORIFID_ALIGN_RIGHT    32964
#define ID_TRACK_HORIFID_ALIGN_LEFTRIGHT 32965
#define ID_TRACK_HORIFID_HORIALIGN_NONE 32966
#define ID_TRACK_HORIFID_ALIGN_TOP      32967
#define ID_TRACK_HORIFID_ALIGN_BOTTOM   32968
#define ID_TRACK_HORIFID_ALIGN_TOPBOTTOM 32969
#define ID_TRACK_HORIFID_VERTALIGN_NONE 32970
#define ID_TRACK_HORIFID_ARRANGLE_LEFT  32971
#define ID_TRACK_HORIFID_ARRANGLE_RIGHT 32972
#define ID_TRACK_HORIFID_ARRANGLE_LEFTRIGHT 32973
#define ID_TRACK_HORIFID_HORIARRANGLE_NONE 32974
#define ID_TRACK_HORIFID_ARRANGLE_TOP   32975
#define ID_TRACK_HORIFID_ARRANGLE_BOTTOM 32976
#define ID_TRACK_HORIFID_ARRANGLE_TOPBOTTOM 32977
#define ID_TRACK_HORIFID_VERTARRANGLE_NONE 32978
#define ID_TRACK_HORIFID_SETWIDTH       32979
#define ID_TRACK_HORIFID_SETHEIGHT      32980
#define ID_TRACK_VERTFID_ALIGN_TOP      32981
#define ID_TRACK_VERTFID_ALIGN_BOTTOM   32982
#define ID_TRACK_VERTFID_ALIGN_TOPBOTTOM 32983
#define ID_TRACK_VERTFID_ALIGN_NONE     32984
#define ID_TRACK_VERTFID_ARRANGLE_LEFT  32985
#define ID_TRACK_VERTFID_ARRANGLE_RIGHT 32986
#define ID_TRACK_VERTFID_ARRANGLE_LEFTRIGHT 32987
#define ID_TRACK_VERTFID_ARRANGLE_NONE  32988
#define ID_TRACK_VERTFID_SETWIDTH       32989
#define ID_TRACK_VERTFID_SETHEIGHT      32990
#define ID_TRACK_TRACK_ARRANGLE_LEFT    32991
#define ID_TRACK_TRACK_ARRANGLE_RIGHT   32992
#define ID_TRACK_TRACK_ARRANGLE_LEFTRIGHT 32993
#define ID_TRACK_TRACK_ARRANGLE_NONE    32994
#define ID_TRACK_TRACK_SETWIDTH         32995
#define ID_TRACK_TRACK_TITLE_SETHEIGHT  32996
#define ID_TRACK_TRACK_TITLE_SETHEIGHT_MAX 32997
#define ID_TRACK_TRCAK_TITLE_HIDE       32998
#define ID_TRACK_TRACK_TITLE_SHOW       32999
#define ID_TRACK_TRACK_HEAD_SETHEIGHT_MAX 33000
#define ID_TRACK_TRACK_HEAD_SETHEIGHT_AUTO 33001
#define ID_BUTTON93325                  33002
#define ID_BUTTON93326                  33003
#define ID_BUTTON93327                  33004
#define ID_BUTTON93328                  33005
#define ID_BUTTON93329                  33006
#define ID_BUTTON93330                  33007
#define ID_BUTTON93331                  33009
#define ID_VIEW_TRACK_ARRANGLE_LEFT     33010
#define ID_VIEW_TRACK_ARRANGLE_RIGHT    33011
#define ID_VIEW_TRACK_ARRANGLE_LEFTRIGHT 33012
#define ID_VIEW_TRACK_HORI_AUTOARANGLE  33014
#define ID_VIEW_TRACK_HORI_SETAUTOARRANGLE 33015
#define ID_VIEW_TRACK_HORI_ARRANGLE     33016
#define ID_VIEW_TRACK_VERT_AUTOALIGN    33017
#define ID_VIEW_TRACK_VERT_SETAUTOALIGN 33018
#define ID_VIEW_TRACK_VERT_ALIGN        33019
#define ID_VIEW_TRACK_ALIGN_TOP         33020
#define ID_VIEW_TRACK_ALIGN_CLIENT      33021
#define ID_VIEW_TRACK_ALIGN_DEPTH       33022
#define ID_VIEW_TRACK_SETWIDTH          33023
#define ID_VIEW_TRACK_HEAD_SETHEIGHT_MAX 33024
#define ID_VIEW_TRACK_HEAD_SETHEIGHT_AUTO 33025
#define ID_VIEW_TRACK_TITLE_HIDE        33026
#define ID_VIEW_TRACK_TITLE_SHOW        33027
#define ID_VIEW_TRACK_TITLE_SETHEIGHT   33028
#define ID_CURVE_VALUE                  33029
#define ID_BUTTON93332                  33029
#define ID_BUTTON93303                  33030
#define ID_BUTTON93304                  33031
#define ID_BUTTON93305                  33032
#define ID_BUTTON93306                  33033
#define ID_BUTTON93307                  33034
#define ID_BUTTON93308                  33035
#define ID_BUTTON93309                  33036
#define ID_BUTTON93310                  33037
#define ID_BUTTON93311                  33038
#define ID_BUTTON93312                  33039
#define ID_BUTTON93313                  33040
#define ID_BUTTON93314                  33041
#define ID_BUTTON93315                  33042
#define ID_BUTTON93316                  33043
#define ID_BUTTON93317                  33044
#define ID_BUTTON93318                  33045
#define ID_BUTTON93319                  33046
#define ID_BUTTON93320                  33047
#define ID_BAO21                        33056
#define ID_BUTTON33057                  33057
#define ID_BUTTON33058                  33058
#define ID_BAO24                        33059
#define ID_FILE_SAVE_BMP                33067
#define ID_DRAW_BMP                     33069
#define ID_HEAD_SPLIT                   33071
#define ID_ADD_RESULT_LIST              33073
#define ID_WAVE                         33074
#define ID_WINDOW_HEAD                  33078
#define ID_PRINT_PAGE_SETUP             33085
#define ID_WELLDATAUPDATE               33089
#define ID_INPUT_RESULT                 33092
#define ID_CORE_DATA                    33093
#define ID_DOCDATA_UPDATE               33097
#define ID_TRACL_LOAD_DATA              33098
#define ID_TRACK_LOAD_DATA              33099
#define ID_DRAW_FOLDLINE                33100
#define ID_DRAW_ARROW                   33101
#define ID_SAVE_OBJECT_BMP              33109
#define ID_INPUT_SCALEFACTOR            33110
#define ID_PRE_RANGVALUE                33111
#define ID_PRE_REWRITE                  33113
#define ID_INSERTPOINT                  33114
#define ID_CURVE_MOUSEEDIT              33121
#define ID_CURVE_DISVALUE               33122
#define IDD_CURVE_MOVEDEP               33124
#define IDD_CURVE_PLUSMOUSE             33125
#define IDD_CURVE_POINTDEP              33126
#define ID_PART_PASTE                   33135
#define IDD_CURVE_DEPICO                33140
#define IDD_CURVE_EDITICO               33141
#define ID_BASELINE                     33142
#define IDD_MODFY_DEPSEGMENT            33143
#define IDD_CURVE_DEPPLUS               33144
#define IDD_LINELOG_CONVERT             33145
#define ID_REMARK                       33146
#define ID_SETREMARKCONMENT             33147
#define ID_MATCHWORKDISK                33148
#define IDD_CURVE_PART_FILTER           33151
#define ID_PARA_SET                     33152
#define IDD_CURVE_NIB                   33153
#define ID_CURVE_POINT_COPY             33154
#define ID_CURVE_COUNTERGLOW            33156
#define IDD_MultiSectDep                33158
#define IDD_PRO_MULTISECTDEP            33159
#define ID_MOUSE_TIP                    33160
#define ID_FILL_LITHGROUND              33161
#define ID_VALUE_SENDTO_CLIPBOARD       33162
#define ID_UP_LAYER                     33163
#define IDC_SCALE_LIST                  33164
#define ID_EDIT_LAYER                   33165
#define ID_PARTCOPY                     33166
#define ID_VIEW_MENUBAR                 33168
#define ID_ADDTO_RESULT                 33169
#define ID_SCALE_WINDOW                 33171
#define ID_SCALE_250                    33172
#define ID_SCALE_200                    33173
#define ID_SACLE_180                    33174
#define ID_SCALE_160                    33175
#define ID_SCALE_140                    33176
#define ID_SCALE_120                    33177
#define ID_SCALE_100                    33178
#define ID_SCALE_90                     33179
#define ID_SCALE_80                     33180
#define ID_SCALE_70                     33181
#define ID_SCALE_60                     33182
#define ID_SCALE_50                     33183
#define ID_SCALE_40                     33184
#define ID_SCALE_30                     33185
#define ID_SCALE_USERSET                33186
#define IDC_FIT_WINDOW                  33187
#define ID_SAVE_DATA                    33188
#define ID_MATCH_ALLOBJECT              33189
#define ID_VIEW_VDLPARABAR              33190
#define ID_VIEW_CURVESTAT               33191
#define ID_VIEW_ENERGY                  33192
#define ID_ADD_IMAGE                    33193
#define ID_ADD_IMAGE3D                  33194
#define ID_ADD_STRATUM                  33195
#define ID_ADD_RESFRACTURE              33196
#define ID_ADD_CONFRACTURE              33197
#define ID_DRAW_STRATUM                 33198
#define ID_MARK_RESFRACTURE             33199
#define ID_MARK_STRATUM                 33200
#define ID_MARK_CONFRACTURE             33201
#define ID_CREAT_IMAGE                  33202
#define ID_EDIT_IMAGEMARK               33203
#define ID_SAVE_IMAGEMARK               33204
#define ID_MARK_AVALANCHE               33205
#define ID_SAVEAS_IMAGEMARK             33206
#define ID_ADD_MARKVECTOR               33207
#define ID_MARK_RESFRACTURE2            33209
#define ID_UPDATE_VECTOR                33210
#define ID_MARK_HOLE                    33211
#define ID_SET_MARKCORREPARA            33212
#define ID_ADD_MARKFREQ                 33213
#define ID_ADD_IMAGECURVE               33214
#define ID_ACCREAT_IMAGE                33215
#define ID_SAVE_IMAGEPRO_PARA           33216
#define ID_EDDY_PLAY                    33217
#define ID_PLAY_STOP                    33218
#define ID_EDDY_RIGHT                   33219
#define ID_ADD_ECHO                     33220
#define ID_ADD_CCL                      33221
#define ID_WRITE_CCL                    33222
#define ID_FREQUENCY                    33223
#define ID_ADD_POLE                     33224
#define ID_KEYSEAT                      33225
#define ID_HOLE_ANALYSIS                33226
#define ID_DIP_PARA                     33227
#define ID_COMPUTE_DIP                  33228
#define ID_DEL_HANDWORK                 33229
#define ID_MODIFY_HANDWORK              33230
#define ID_MARK_LAYERFRACTURE           33234
#define ID_MARK_CCL                     33235
#define ID_VIEW_DOCBAR                  33236
#define ID_COUNT_CONTOUR                33237
#define ID_DEL_SELHOLE                  33238
#define ID_DEL_SMALL_SEL                33239
#define ID_DEL_BIG_SEL                  33240
#define IDS_OBJECT_POS                  61446
#define IDS_OBJECT_WH                   61447
#define IDS_DIP_SCOPE_ERROR             61448
#define IDS_DEPTH_SCOPE_ERROR           61449
#define IDS_NOT_MATCH_DEPTHUNIT         61450
#define IDS_NO_CURVE                    61451
#define IDS_CURVE_ALIASNAME_ER          61452
#define IDS_CANNT_INPUT_FILE            61453
#define IDS_NO_DRAW_FILE                61454
#define IDS_UNKNOWN_FILEFORMAT          61455
#define IDS_OPEN_TEMPLATE_FAILURE       61456
#define IDS_MATCH_DEPTH                 61457
#define IDS_TEXT_VERSION_ERROR          61458
#define IDS_MARGIN_TOO_BIG              61459
#define IDS_HEADMAR_TOO_BIG             61460
#define IDS_CANNT_OPEN_FILE             61461
#define IDS_FILELINE_TOOLONG            61462
#define IDS_FILE_NOT_EXIST              61463
#define IDS_TRACK_TOO_SMALL             61464
#define IDS_NORMAL_TOOLBAR              61465
#define IDS_PLOT_TOOLBAR                61466
#define IDS_ARRAY_TOOLBAR               61467
#define IDS_GRAG_ANGLE                  61468
#define IDS_DRAG_ANGLE                  61468
#define IDS_WIDTH_HEIGT                 61469
#define IDS_FILTER1                     61470
#define IDS_FILTER2                     61471
#define IDS_FILTER3                     61472
#define IDS_FILTER4                     61473
#define IDS_DIPPROPERTIES               61474
#define IDS_FRAMELINE                   61475
#define IDS_FRAMEFILL                   61476
#define IDS_ALIASFONT                   61477
#define IDS_ZERFONT                     61478
#define IDS_FREQUENCYSTATISTIC          61479
#define IDS_DAZFREQUENCYPROPERTIES      61480
#define IDS_DIPFREQUENCY                61481
#define IDS_INPUTALIAS                  61482
#define IDS_SELECTFONT                  61483
#define IDS_FIDALIAS                    61484
#define IDS_DRAWINGPROPERTIES           61485
#define IDS_LINEPROPERTIES              61486
#define IDS_FILLPROPERTIES              61487
#define IDS_DRAGMOUSE                   61488
#define IDS_LOCATION                    61489
#define IDS_LEFTBOUNDARY                61490
#define IDS_RIGHTBOUNDARY               61491
#define IDS_HEADHEIGHT                  61492
#define IDS_WIDTHHEIGHT                 61493
#define IDS_LOCATION1                   61494
#define IDS_WIDTH                       61495
#define IDS_HEADHEIGHT1                 61496
#define IDS_CURVEDLG                    61497
#define IDS_DEPTH                       61498
#define IDS_VALUE                       61499
#define IDS_NORMAL                      61500
#define IDS_ADD                         61501
#define IDS_SUBTRACT                    61502
#define IDS_ABSOLUTE                    61503
#define IDS_NO                          61511
#define IDS_DRAGCHANGE                  61512
#define IDS_RESULTFONT                  61513
#define IDS_NOTESTEXT                   61514
#define IDS_START                       61515
#define IDS_TEXTPROPERTIES              61516
#define IDS_TEXTFILEPROPERTIES          61517
#define IDS_TRACK                       61518
#define IDS_DEPTH1                      61519
#define IDS_TRACKPROPERTIES             61520
#define IDS_HEADFILL                    61521
#define IDS_ZERHEADFILL                 61522
#define IDS_DRAWREGIONFILL              61523
#define IDS_HEADTEXT                    61524
#define IDS_DEPTHHEADTEXT               61525
#define IDS_DEPTHFONT                   61526
#define IDS_INPUTTRACKNAME              61527
#define IDS_GRIDPROPERTIES              61528
#define IDS_TRACKNAME                   61529
#define IDS_INPUTDEPTHHEADNAME          61530
#define IDS_DEPTHNAME                   61531
#define IDS_DEPTHLEFTBROUNDARY          61532
#define IDS_DEPTHLEFTBOUNDARY           61532
#define IDS_DEPTHRIGHTBROUNDARY         61533
#define IDS_DEPTHRIGHTBOUNDARY          61533
#define IDS_TITLEHEIGHT                 61534
#define IDS_WAVEFULLPROPERTIES          61535
#define IDS_DEPTHREGIONFILL             61536
#define IDS_HEIGHT                      61537
#define IDS_FILEPROPERTIES              61538
#define IDS_DLGBMP_CLIPBOARD            61539
#define IDS_HAND_IDENTIFY               61540
#define IDS_HOLE_KEYSEAT                61541
#define IDS_HOLE_BREAKOUT               61542
#define IDS_HOLE_SLIP                   61543
#define IDS_HOLE_CLEAR                  61544
#define ID_BMP_SENTTOCILP               61545

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        878
#define _APS_NEXT_COMMAND_VALUE         1822
#define _APS_NEXT_CONTROL_VALUE         1864
#define _APS_NEXT_SYMED_VALUE           806
#endif
#endif
