//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FlowChart.rc
//
#define IDD_FLOWCHART_FORM              101
#define IDR_HTML_PORCOMPUTDLG           103
#define IDR_MAINFRAME                   128
#define IDR_FLOWTYPE                    129
#define IDB_TOOLBAR_HOT                 132
#define IDD_BACKUPWELLDATA_RUNDLG       133
#define IDD_BACKUPDLG                   134
#define IDD_PADDEPCORDLG                135
#define IDD_BUTTONCORDLG                136
#define IDD_UNITEDLG                    137
#define IDD_IMGCREATDLG                 138
#define IDD_IMGTONEUPDLG                139
#define IDD_POISEDLG                    140
#define IDD_RMFSCALEDLG                 141
#define IDD_DIPCOMPUTE_DIALOG           142
#define IDD_DIALOG1                     143
#define IDD_PROJECT_DLG                 143
#define IDI_ICON1                       144
#define IDI_ICON2                       146
#define IDI_ICON3                       147
#define IDD_THICKCPDLG                  148
#define IDD_CRACKDLG                    149
#define IDD_HOLE_ANALYSIS               150
#define IDD_POROSPECT_DLG               151
#define IDD_DIFF_DLG                    152
#define IDD_ABNORMAL_DLG                154
#define IDD_ANISOTROPYDLG               155
#define IDC_TREE1                       1000
#define IDC_COMBO_SERIES                1001
#define IDC_MESSAGEBOX                  1002
#define IDC_STPRODEP                    1003
#define IDC_ENPRODEP                    1004
#define IDC_PROGRESS1                   1005
#define IDC_LIST_CURVE                  1006
#define IDC_STATIC_TODO                 1007
#define IDC_EDIT3                       1008
#define IDC_STATIC_TODO2                1008
#define IDC_EDIT4                       1009
#define IDC_NAME                        1010
#define IDC_STATIC_TODO3                1010
#define IDC_EDIT1                       1011
#define IDC_LIST1                       1012
#define IDC_EDIT24                      1012
#define IDC_WINLENGTH                   1013
#define IDC_WINLENGTH2                  1014
#define IDC_FILTER                      1015
#define IDC_GRADS                       1016
#define IDC_EXPEND                      1017
#define IDC_SQUARE                      1018
#define IDC_FREQ                        1019
#define IDC_COMBO1                      1020
#define IDC_EDIT2                       1021
#define IDC_EDIT5                       1022
#define IDC_COMBO2                      1023
#define IDC_CHECK1                      1024
#define IDC_CHECK2                      1025
#define IDC_CHECK3                      1026
#define IDC_CHECK4                      1027
#define IDC_CHECK5                      1028
#define IDC_CHECK6                      1029
#define IDC_BUTTON3                     1030
#define IDC_WIN_LENGTH                  1031
#define IDC_SEARCH_LENGTH               1032
#define IDC_STEP_LENGTH                 1033
#define IDC_COMBO3                      1034
#define IDC_CHECK7                      1035
#define IDC_MUSIC                       1036
#define IDC_MIN_COEF                    1039
#define IDC_MAX_DIP                     1040
#define IDC_MIN_COEF2                   1041
#define IDC_MIN_COEF3                   1042
#define IDC_BUTTON2                     1044
#define IDC_COMBO_RMFNAME               1045
#define IDC_RMFWELL                     1046
#define IDC_STATIC_MIN                  1047
#define IDC_STATIC_MAX                  1048
#define IDC_STATIC_MAX2                 1049
#define IDC_BUTTON4                     1050
#define IDC_STATIC_MAX6                 1050
#define IDC_RADIO1                      1051
#define IDC_STATIC_MIN2                 1051
#define IDC_RADIO2                      1052
#define IDC_STATIC_MIN3                 1052
#define IDC_RADIO3                      1053
#define IDC_STATIC_MIN4                 1053
#define IDC_EDIT_PROENDEP               1054
#define IDC_STATIC_SDEP2                1055
#define IDC_RADIO4                      1056
#define IDC_BROWSWELL                   1057
#define IDC_RADIO5                      1057
#define IDC_EDIT8                       1058
#define IDC_RADIO6                      1058
#define IDC_BITS                        1059
#define IDC_EDIT9                       1060
#define IDC_EDIT10                      1061
#define IDC_EDIT11                      1062
#define IDC_BUTTON1                     1063
#define IDC_EDIT12                      1064
#define IDC_EDIT13                      1065
#define IDC_EDIT14                      1066
#define IDC_EDIT23                      1067
#define IDC_EDIT18                      1068
#define IDC_EDIT16                      1069
#define IDC_EDIT17                      1070
#define IDC_EDIT20                      1071
#define IDC_EDIT15                      1072
#define IDC_EDIT21                      1073
#define IDC_EDIT19                      1074
#define IDC_EDIT6                       1075
#define IDC_EDIT7                       1076
#define IDC_EDIT22                      1077
#define IDC_BUTTON5                     1078
#define IDC_STATIC_DEP                  1079
#define IDC_STATIC_MAX3                 1080
#define IDC_STATIC_MAX4                 1082
#define IDC_STATIC_SDEP                 1083
#define IDC_STATIC_MAX5                 1083
#define IDC_EDIT_PROSTDEP               1084
#define IDC_STATIC_EDEP                 1085
#define ID_VIEW_MENUBAR                 32771
#define ID_RUN                          32772
#define ID_DEL                          32773
#define ID_ADD_NODE                     32774
#define ID_SHOW_FRAM                    32776
#define ID_DEL_DATABUF                  32778
#define ID_RUN_ALL                      32779
#define IDS_INCURVE                     61446
#define IDS_RELOC                       61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
